name: GitHub Actions Demo
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Serve project
        run: npm run dev &
      - name: Wait for server to be ready
        run: npx wait-on http://localhost:3000
      - name: Cypress run
        uses: cypress-io/github-action@v6
      - uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
