name: GitHub Actions Demo
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci
      - run: npm run build
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Adding Known Hosts
        run: ssh-keyscan -H 151.80.58.182 >> ~/.ssh/known_hosts
      - name: Push with scp
        run: scp -r dist/* debian@151.80.58.182
